### PR TITLE
Fix US05

### PR DESCRIPTION
**Pull request by Jean-Beru**
Issue #32

### CODE REVIEW

**Comment by salahm** [comment]
:+1:

**Comment by florianbelhomme** [comment]
squash your commits for the PR (surtout si c'est 5 lignes changées)

**Comment by Jean-Beru** [comment]
Should I squash before propose PR or just before merge?

**Comment by ogizanagi** [comment]
@Jean-Beru : Squash before creating the PR.
Then, add commit per review in order to keep it readable for reviewers.
Finally, squash when the PR is ready to be merged.

**Comment by Jean-Beru** [comment]
OK thx!

**Comment by florianbelhomme** [comment]
:+1: for the max's tip

Another tip : close the branch when you merge it, it avoid confusion later. And it keep the repo clean.

**Comment by ogizanagi** [comment]
Also close related issue(s).

**Pull request merged**
