### PR TITLE
Fix US06

### PR DESCRIPTION
**Pull request by Jean-Beru**
Issue #33

### CODE REVIEW

**Comment by romqin** [comment]
in [src/SensioLabs/JobBoardBundle/Service/Mailer.php](https://github.com/poledev/hubert/blob/issue-33/src/SensioLabs/JobBoardBundle/Service/Mailer.php#L31-L36), you should like this:
```php
use Psr\Log\NullLogger;

public function __construct(/** ... */, LoggerInterface $logger = null)
{
    // ...
    $this->logger = $logger ?: new NullLogger();
}
```

[source](https://speakerdeck.com/lyrixx/symfony-live-2015-paris-monitorer-sa-prod?slide=19)

**Comment by Jean-Beru** [comment]
@romqin Right! It's done ;)

**Comment by ogizanagi** [comment]
Ideally, you should not embed a whole third-party library like ckeditor in your versioning but use proper packages managers.

**Comment by Jean-Beru** [comment]
I know, I usually use bower. But, in this case, it will be the only third-party library. So using bower may be a little bit over engineering. No?

**Comment by ogizanagi** [comment]
Absolutely not. :smile_cat: 
I'd even prefer you using composer for this if you do not want to use bower: http://tech.arendjantetteroo.nl/blog/2013/11/06/switching-from-bower-to-composer-with-components/

**Comment by Jean-Beru** [comment]
If I want to use Bower, I will add a dependency to NodeJS. Futhermore, ckeditor will be versionned (see: http://symfony.com/doc/current/cookbook/frontend/bower.html)

I tried to add ckeditor with composer but it try to get some files during loading (language, config, ...). But theses files are in `vendor` folder, so they cannot be accessed.

So I keep the actual solution as long as I haven't a simplest one.

**Comment by ogizanagi** [comment]
Of course, you have to change the component dir to publish it in web:
```json
"config": {
        "component-dir": "web/components"
 }
```

**Comment by Jean-Beru** [comment]
It concerns only component/* packages. ckeditor's package name is ckeditor/ckeditor so it's installed in `vendor`. I also tried :
```
"extra":{
    "component": {
        "ckeditor/ckeditor": {
            "cmoponent-dir": "web/assets/vendor"
        }
    }
}
```
But without success

**Comment by ogizanagi** [comment]
Okay for merge I'll guess ^^'

**Pull request merged**
